/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.Component;

import javax.swing.JOptionPane;

/**
 *
 * @author Saidi
 */
public class Content_bg extends javax.swing.JPanel {

    /**
     * Creates new form Content_bg
     */
    public Content_bg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dashbord = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dataKonsul = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKonsul = new javax.swing.JTable();
        jLabel64 = new javax.swing.JLabel();
        btTambah2 = new javax.swing.JButton();
        dataDokter = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        btTambah1 = new javax.swing.JButton();
        about = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dataPasien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btTambah = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dashbord.setBackground(new java.awt.Color(255, 255, 255));
        dashbord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Selengkapnya");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel8KeyPressed(evt);
            }
        });
        dashbord.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 80, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel12.setText("0");
        dashbord.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 40, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Lihat Selengkapnya                  ->");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        dashbord.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Menjaga kesehatan anda, itu tugas kami");
        dashbord.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 270, -1));
        dashbord.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Lihat Selengkapnya              ->");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        dashbord.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Lihat Selengkapnya                -> ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        dashbord.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 220, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel15.setText("Jauh Heatlink");
        dashbord.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel16.setText("mengenal lebih ");
        dashbord.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel17.setText("Betugas");
        dashbord.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel14.setText("Data Dokter yang ");
        dashbord.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel13.setText("0");
        dashbord.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 40, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel19.setText("Data Pasien Yang");
        dashbord.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel20.setText("Sedang Dirawat");
        dashbord.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));
        dashbord.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard (7).png"))); // NOI18N
        dashbord.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -260, 1950, 1060));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel18.setText("0");
        dashbord.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 40, -1));

        mainPanel.add(dashbord, "card2");

        dataKonsul.setBackground(new java.awt.Color(255, 255, 255));
        dataKonsul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKonsul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKonsul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKonsulMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKonsul);

        dataKonsul.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 1040, 360));

        jLabel64.setBackground(new java.awt.Color(102, 102, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 255));
        jLabel64.setText("Konsultasi");
        dataKonsul.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btTambah2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btTambah2.setForeground(new java.awt.Color(0, 0, 0));
        btTambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/back_1.png"))); // NOI18N
        btTambah2.setText("Back");
        btTambah2.setToolTipText("");
        btTambah2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTambah2MouseClicked(evt);
            }
        });
        btTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambah2ActionPerformed(evt);
            }
        });
        dataKonsul.add(btTambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 130, 50));

        mainPanel.add(dataKonsul, "card2");

        dataDokter.setBackground(new java.awt.Color(255, 255, 255));
        dataDokter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDokter);

        dataDokter.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1100, 360));

        jLabel22.setBackground(new java.awt.Color(102, 102, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Data dokter");
        dataDokter.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btTambah1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btTambah1.setForeground(new java.awt.Color(0, 0, 0));
        btTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/back_1.png"))); // NOI18N
        btTambah1.setText("Back");
        btTambah1.setToolTipText("");
        btTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambah1ActionPerformed(evt);
            }
        });
        dataDokter.add(btTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 130, 50));

        mainPanel.add(dataDokter, "card2");

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ABOUT (1).png"))); // NOI18N
        about.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        mainPanel.add(about, "card3");

        dataPasien.setBackground(new java.awt.Color(255, 255, 255));
        dataPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPasien);

        dataPasien.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1030, 380));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Data Pasient");
        dataPasien.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, -1));

        btTambah.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btTambah.setForeground(new java.awt.Color(0, 0, 0));
        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/back_1.png"))); // NOI18N
        btTambah.setText("Back");
        btTambah.setToolTipText("");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        dataPasien.add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 130, 50));

        mainPanel.add(dataPasien, "card2");

        jLabel11.setText("jLabel11");
        mainPanel.add(jLabel11, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyPressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(about);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_jLabel8KeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          mainPanel.removeAll();
        mainPanel.add(about);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:
        // Mendapatkan baris yang diklik
        int baris = tblPasien.rowAtPoint(evt.getPoint());

        // Ambil idPasien dari kolom kedua yang sesuai (indeks 1)
//        String idPasien = tblPasien.getValueAt(baris, 4).toString();
//        String namaPasien = tblPasien.getValueAt(baris, 1).toString();
//        String jenisKelamin = tblPasien.getValueAt(baris, 2).toString();
//        String alamat = tblPasien.getValueAt(baris, 3).toString();

        // Set data ke form edit
//        txtEditNamaPasien.setText(namaPasien);
//        txtEditAlamat.setText(alamat);
//        txtHiddenIdPasien.setText(idPasien);  // ID Pasien diset di sini
//        cbJenisKelamin.setSelectedItem(jenisKelamin);
    }//GEN-LAST:event_tblPasienMouseClicked

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dashbord);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_btTambahActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataPasien);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tblDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokterMouseClicked
        // TODO add your handling code here:
        int baris = tblDokter.rowAtPoint(evt.getPoint());
        String namaDokter = tblDokter.getValueAt(baris, 1).toString(); // Kolom 1: namaDokter
        String spesialis = tblDokter.getValueAt(baris, 2).toString(); // Kolom 2: spesialis
        String jenisKelamin = tblDokter.getValueAt(baris, 3).toString(); // Kolom 3: jenisKelamin
        String ruangan = tblDokter.getValueAt(baris, 4).toString(); // Kolom 4: ruangan
        String idDokter = tblDokter.getValueAt(baris, 5).toString(); // Kolom 5: idDokter (tersembunyi)
        String username = tblDokter.getValueAt(baris, 6).toString(); // Kolom 5: idDokter (tersembunyi)

        // Set data ke form edit
//        txtEditNamaDokter1.setText(namaDokter);
//        txtEditSpesialis.setText(spesialis);
//        txtEditRuangan.setText(ruangan);
//        txtHiddenIdDokter.setText(idDokter); // ID Dokter disimpan di komponen hidden
//        cbEditJenisKelamin.setSelectedItem(jenisKelamin); // Pilih jenis kelamin pada ComboBox
//        cbEditUsername.setSelectedItem(username); // Pilih jenis kelamin pada ComboBox
    }//GEN-LAST:event_tblDokterMouseClicked

    private void btTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTambah1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblKonsulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKonsulMouseClicked
        // TODO add your handling code here:
        //        int baris = tblKonsul.rowAtPoint(evt.getPoint());
        //
        //// Ambil nilai dari kolom yang sesuai dengan pemeriksaan null
        //        String idKonsultasi = (tblKonsul.getValueAt(baris, 1) != null) ? tblKonsul.getValueAt(baris, 1).toString() : ""; // ID Konsultasi
        //        String idPasien = (tblKonsul.getValueAt(baris, 2) != null) ? tblKonsul.getValueAt(baris, 2).toString() : ""; // ID Pasien
        //        String idDokter = (tblKonsul.getValueAt(baris, 3) != null) ? tblKonsul.getValueAt(baris, 3).toString() : ""; // ID Dokter
        //        String waktuKonsultasi = (tblKonsul.getValueAt(baris, 4) != null) ? tblKonsul.getValueAt(baris, 4).toString() : ""; // Waktu Konsultasi
        //        String catatan = (tblKonsul.getValueAt(baris, 5) != null) ? tblKonsul.getValueAt(baris, 5).toString() : ""; // Catatan
        //        String keperluanPasien = (tblKonsul.getValueAt(baris, 6) != null) ? tblKonsul.getValueAt(baris, 6).toString() : ""; // Keperluan Pasien
        //
        //// Menampilkan data yang dipilih ke field yang sesuai
        //        txtHiddenIdKonsul.setText(idKonsultasi); // Menyimpan ID Konsultasi
        //
        //        cbEditNamaDokter.setSelectedItem(idDokter); // Menyimpan ID Dokter
        //
        //// Menampilkan data lainnya yang relevan ke field yang sesuai
        //        txtWaktu.setText(waktuKonsultasi);
        //        txtKeluhan.setText(keperluanPasien);
        //
        //// Jika perlu menampilkan nama dokter, bisa ditambahkan pencarian nama berdasarkan ID Dokter
        ////        String namaDokter = getNamaDokterById(Integer.parseInt(idDokter)); // Misalkan ada metode untuk mendapatkan nama dokter berdasarkan ID
        ////        cbEditNamaDokter.setSelectedItem(namaDokter); // Menetapkan nama dokter di comboBox

    }//GEN-LAST:event_tblKonsulMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(dataKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTambah2ActionPerformed

    private void btTambah2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTambah2MouseClicked
        // TODO add your handling code here:
         mainPanel.removeAll();
        mainPanel.add(dashbord);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btTambah2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btTambah1;
    private javax.swing.JButton btTambah2;
    private javax.swing.JPanel dashbord;
    private javax.swing.JPanel dataDokter;
    private javax.swing.JPanel dataKonsul;
    private javax.swing.JPanel dataPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTable tblKonsul;
    private javax.swing.JTable tblPasien;
    // End of variables declaration//GEN-END:variables
}
