/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.Component;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Config;
import static model.Config.writeLog;

/**
 *
 * @author Saidi
 */
public class Form_profilPasien extends javax.swing.JPanel {

    private void loadData(int idPasien) {
        try {
            // Query untuk mendapatkan data pasien berdasarkan idPasien
            String sqlSelect = "SELECT * FROM t_pasien WHERE idPasien = ?";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
            pstSelect.setInt(1, idPasien); // Menggunakan idPasien untuk filter
            java.sql.ResultSet rs = pstSelect.executeQuery();

            if (rs.next()) {
                // Set text field dengan data pasien yang diambil
                txtNamaProfilePasien.setText(rs.getString("namaPasien"));
                cbJenisKelaminProfilePasien.setSelectedItem(rs.getString("jenisKelamin"));
                txtAlamatPasien.setText(rs.getString("alamat"));
                txtHiddenProfile.setText(String.valueOf(idPasien)); // Set idPasien di hidden field
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data pasien: " + e.getMessage());
        }
    }

    /**
     * Creates new form Form_User
     */
    public Form_profilPasien(int idPasien, String namaPasien, String jenisKelamin, String alamat) {
        initComponents();
//        load_table();
        txtHiddenProfile.setVisible(false);
        txtHiddenProfile.setText(String.valueOf(idPasien));
        loadData(idPasien);
//        txtAlamatPasien.setText(alamat);
//        txtNamaProfilePasien.setText(namaPasien);
//        cbJenisKelaminProfilePasien.setSelectedItem(jenisKelamin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        editUSer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btEditSimpan = new javax.swing.JButton();
        btBatal1 = new javax.swing.JButton();
        cbJenisKelaminProfilePasien = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNamaProfilePasien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAlamatPasien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHiddenProfile = new javax.swing.JTextField();
        cbLevel3 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        editUSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Edit Biodata");
        editUSer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        btEditSimpan.setText("Simpan");
        btEditSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditSimpanActionPerformed(evt);
            }
        });
        editUSer.add(btEditSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 100, 30));

        btBatal1.setText("Batal");
        btBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatal1ActionPerformed(evt);
            }
        });
        editUSer.add(btBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 73, 100, 30));

        cbJenisKelaminProfilePasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cbJenisKelaminProfilePasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminProfilePasienActionPerformed(evt);
            }
        });
        editUSer.add(cbJenisKelaminProfilePasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 460, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Nama");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Jenis Kelamin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224)
                                .addComponent(txtHiddenProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAlamatPasien)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNamaProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 1447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHiddenProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editUSer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cbLevel3.setBackground(new java.awt.Color(153, 153, 255));
        cbLevel3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1 (User)", "Level 2 (Pegawai)", "Level 3 (Admin)" }));
        editUSer.add(cbLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 224, 364, -1));

        mainPanel.add(editUSer, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btEditSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditSimpanActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
//        mainPanel.add(dataUser);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            // Memeriksa apakah Nama Pasien kosong
            if ("".equals(txtNamaProfilePasien.getText())) {
                JOptionPane.showMessageDialog(this, "Isikan Nama Pasien terlebih dahulu");
            } else {
                // Menyusun query untuk update data pasien berdasarkan idPasien
                String sqlUpdate = "UPDATE t_pasien SET namaPasien = '" + txtNamaProfilePasien.getText()
                        + "', jenisKelamin = '" + cbJenisKelaminProfilePasien.getSelectedItem().toString()
                        + "', alamat = '" + txtAlamatPasien.getText()
                        + "' WHERE idPasien = '" + txtHiddenProfile.getText() + "'";

                // Membuka koneksi ke database
                java.sql.Connection conn = (Connection) Config.configDB();

                // Menyiapkan statement dan mengeksekusi query update
                java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                pstUpdate.execute();

                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(null, "Data Pasien Berhasil Diperbaharui dengan Nama " + txtNamaProfilePasien.getText());
                writeLog("Data Pasien Berhasil Diperbaharui dengan ID Pasien " + txtHiddenProfile.getText());

                // Setelah data diperbarui, ambil data terbaru
                String sqlSelect = "SELECT * FROM t_pasien WHERE idPasien = ?";
                java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
                pstSelect.setInt(1, Integer.parseInt(txtHiddenProfile.getText())); // ID pasien yang disembunyikan

                java.sql.ResultSet rs = pstSelect.executeQuery();
                if (rs.next()) {
                    // Update text field dengan data terbaru
                    txtNamaProfilePasien.setText(rs.getString("namaPasien"));
                    cbJenisKelaminProfilePasien.setSelectedItem(rs.getString("jenisKelamin"));
                    txtAlamatPasien.setText(rs.getString("alamat"));
                }
            }
        } catch (Exception e) {
            // Menampilkan pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
            writeLog("Perubahan Data Gagal : " + e.getMessage());
        }
    }//GEN-LAST:event_btEditSimpanActionPerformed

    private void btBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatal1ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
//        mainPanel.add(dataUser);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btBatal1ActionPerformed

    private void cbJenisKelaminProfilePasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminProfilePasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelaminProfilePasienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal1;
    private javax.swing.JButton btEditSimpan;
    private javax.swing.JComboBox<String> cbJenisKelaminProfilePasien;
    private javax.swing.JComboBox<String> cbLevel3;
    private javax.swing.JPanel editUSer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAlamatPasien;
    private javax.swing.JTextField txtHiddenProfile;
    private javax.swing.JTextField txtNamaProfilePasien;
    // End of variables declaration//GEN-END:variables
}
