/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.Component;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;        // Untuk eksekusi query SQL\
import javax.swing.table.DefaultTableModel;
import model.Config;
import static model.Config.writeLog;

/**
 *
 * @author Saidi
 */
public class Form_DataKonsul extends javax.swing.JPanel {

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Konsultasi");
        model.addColumn("ID Pasien");
        model.addColumn("ID Dokter");
        model.addColumn("Waktu Konsultasi");
        model.addColumn("Catatan");
        model.addColumn("Keperluan Pasien");

        try {
            int no = 1;
            String sql = "SELECT * FROM t_konsultasi";
            Connection conn = Config.configDB();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString("idKonsultasi"),
                    res.getString("idPasien"),
                    res.getString("idDokter"),
                    res.getString("waktuKonsultasi"),
                    res.getString("catatan"),
                    res.getString("keperluanPasien")
                });
            }
            tblKonsultasi.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data tidak dapat ditampilkan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void relasiDokter() {
        try {
            Connection conn = Config.configDB();
            String sql = "SELECT idDokter, namaDokter FROM t_dokter";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cbTambahNamaDokter.removeAllItems();
            cbEditNamaDokter.removeAllItems();

            while (rs.next()) {
                String item = rs.getString("namaDokter") + " (ID: " + rs.getInt("idDokter") + ")";
                cbTambahNamaDokter.addItem(item);
                cbEditNamaDokter.addItem(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data dokter: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void relasiPasien() {
        try {
            Connection conn = Config.configDB();
            String sql = "SELECT idPasien, namaPasien FROM t_pasien";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cbTambahNamaPasien.removeAllItems();
            cbEditNamaPasien.removeAllItems();

            while (rs.next()) {
                String item = rs.getString("namaPasien") + " (ID: " + rs.getInt("idPasien") + ")";
                cbTambahNamaPasien.addItem(item);
                cbEditNamaPasien.addItem(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data pasien: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form Form_DataKonsul
     */
    public Form_DataKonsul() {
        initComponents();
        load_table();
        relasiDokter();
        relasiPasien();
        txtHiddenIdKonsultasi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        dataKonsul = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKonsultasi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btTambah = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editKonsul = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbEditNamaDokter = new javax.swing.JComboBox<>();
        cbEditNamaPasien = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtEditWaktu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtHiddenIdKonsultasi = new javax.swing.JTextField();
        txtEditKeluhan1 = new javax.swing.JTextField();
        txtEditCatatan1 = new javax.swing.JTextField();
        btSimpanKonsul = new javax.swing.JButton();
        btBatalKonsul = new javax.swing.JButton();
        cbLevel3 = new javax.swing.JComboBox<>();
        jLabel63 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tambahKonsul = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbTambahNamaDokter = new javax.swing.JComboBox<>();
        cbTambahNamaPasien = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtKeluhan = new javax.swing.JTextField();
        txtCatatan = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        btBatal = new javax.swing.JButton();
        btSimpan = new javax.swing.JButton();
        cbLevel1 = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataKonsul.setBackground(new java.awt.Color(255, 255, 255));
        dataKonsul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKonsultasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKonsultasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKonsultasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKonsultasi);

        dataKonsul.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1060, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dataKonsul.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 400, -1));

        jLabel22.setBackground(new java.awt.Color(102, 102, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("data hasil konsultasi");
        dataKonsul.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btTambah.setBackground(new java.awt.Color(195, 224, 253));
        btTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pngtree-blue-plus-concept-icon-on-white-background-png-image_8159235-removebg-preview 1.png"))); // NOI18N
        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        dataKonsul.add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 130, 50));

        bt_edit.setBackground(new java.awt.Color(129, 179, 251));
        bt_edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image 12.png"))); // NOI18N
        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });
        dataKonsul.add(bt_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 120, 50));

        jButton3.setBackground(new java.awt.Color(195, 224, 253));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image 10.png"))); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        dataKonsul.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 130, 50));

        mainPanel.add(dataKonsul, "card2");

        editKonsul.setBackground(new java.awt.Color(255, 255, 255));
        editKonsul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Nama Dokter");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Keluhan");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Catatan");

        txtEditWaktu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditWaktu.setToolTipText("");
        txtEditWaktu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditWaktutxtid1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Waktu Konsultasi");

        txtEditKeluhan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditKeluhan1.setToolTipText("");
        txtEditKeluhan1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditKeluhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditKeluhan1txtid1ActionPerformed(evt);
            }
        });

        txtEditCatatan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditCatatan1.setToolTipText("");
        txtEditCatatan1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditCatatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditCatatan1txtid1ActionPerformed(evt);
            }
        });

        btSimpanKonsul.setBackground(new java.awt.Color(195, 224, 253));
        btSimpanKonsul.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btSimpanKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector.png"))); // NOI18N
        btSimpanKonsul.setText("Simpan");
        btSimpanKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanKonsulActionPerformed(evt);
            }
        });

        btBatalKonsul.setBackground(new java.awt.Color(204, 255, 255));
        btBatalKonsul.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btBatalKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Group 2803.png"))); // NOI18N
        btBatalKonsul.setText("Batal");
        btBatalKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalKonsulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btSimpanKonsul)
                        .addGap(30, 30, 30)
                        .addComponent(btBatalKonsul, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbEditNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302)
                        .addComponent(txtHiddenIdKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbEditNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditKeluhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditCatatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 584, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEditNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHiddenIdKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditKeluhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtEditCatatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBatalKonsul, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSimpanKonsul, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        editKonsul.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 510));

        cbLevel3.setBackground(new java.awt.Color(153, 153, 255));
        cbLevel3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1 (User)", "Level 2 (Pegawai)", "Level 3 (Admin)" }));
        editKonsul.add(cbLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 224, 364, -1));

        jLabel63.setBackground(new java.awt.Color(102, 102, 255));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(51, 51, 255));
        jLabel63.setText("Edit Data Konsultasi");
        editKonsul.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Nama Pasien");
        editKonsul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 243, -1));

        mainPanel.add(editKonsul, "card2");

        tambahKonsul.setBackground(new java.awt.Color(255, 255, 255));
        tambahKonsul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nama Dokter");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Nama Pasien");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Keluhan");

        cbTambahNamaDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Waktu Konsultasi");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Catatan");

        txtKeluhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKeluhan.setToolTipText("");
        txtKeluhan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtKeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluhantxtid1ActionPerformed(evt);
            }
        });

        txtCatatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCatatan.setToolTipText("");
        txtCatatan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtCatatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatatantxtid1ActionPerformed(evt);
            }
        });

        txtWaktu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtWaktu.setToolTipText("");
        txtWaktu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktutxtid1ActionPerformed(evt);
            }
        });

        btBatal.setBackground(new java.awt.Color(195, 224, 253));
        btBatal.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image 10.png"))); // NOI18N
        btBatal.setText("Batal");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        btSimpan.setBackground(new java.awt.Color(204, 255, 255));
        btSimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTambahNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTambahNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 464, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtWaktu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                            .addComponent(txtCatatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKeluhan, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btSimpan)
                .addGap(31, 31, 31)
                .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTambahNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTambahNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        tambahKonsul.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 860, 510));

        cbLevel1.setBackground(new java.awt.Color(153, 153, 255));
        cbLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1 (User)", "Level 2 (Pegawai)", "Level 3 (Admin)" }));
        tambahKonsul.add(cbLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 224, 364, -1));

        jLabel64.setBackground(new java.awt.Color(102, 102, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 255));
        jLabel64.setText("Tambah data konsultasi");
        tambahKonsul.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        mainPanel.add(tambahKonsul, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(dataKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();
        try {
            String sql = "INSERT INTO t_konsultasi (idPasien, idDokter, waktuKonsultasi, catatan, keperluanPasien) VALUES (?, ?, ?, ?, ?)";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mengambil nilai dari ComboBox dan TextField
            String pasienItem = cbTambahNamaPasien.getSelectedItem().toString();
            String dokterItem = cbTambahNamaDokter.getSelectedItem().toString();

            // Pastikan format nama (ID: 1)
            int idPasien = Integer.parseInt(pasienItem.substring(pasienItem.indexOf("ID:") + 3, pasienItem.indexOf(")")).trim());
            int idDokter = Integer.parseInt(dokterItem.substring(dokterItem.indexOf("ID:") + 3, dokterItem.indexOf(")")).trim());

            String waktuKonsultasi = txtWaktu.getText();
            String catatan = txtCatatan.getText();
            String keperluanPasien = txtKeluhan.getText();

            // Mengisi parameter ke query
            pst.setInt(1, idPasien); // idPasien
            pst.setInt(2, idDokter); // idDokter
            pst.setString(3, waktuKonsultasi); // waktuKonsultasi
            pst.setString(4, catatan); // catatan
            pst.setString(5, keperluanPasien); // keperluanPasien

            // Menjalankan query
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            writeLog("Penyimpanan Data Berhasil untuk Konsultasi dengan ID Pasien: " + idPasien + " dan ID Dokter: " + idDokter);

            // Muat ulang tabel dan bersihkan form
            load_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan: " + e.getMessage());
            writeLog("Data gagal disimpan: " + e.getMessage());
        }


    }//GEN-LAST:event_btSimpanActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();


    }//GEN-LAST:event_btTambahActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:

        mainPanel.removeAll();
        mainPanel.add(dataKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_btBatalActionPerformed

    private void tblKonsultasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKonsultasiMouseClicked
        // TODO add your handling code here:
        int baris = tblKonsultasi.rowAtPoint(evt.getPoint());

        if (baris >= 0) {
            Object objIdKonsultasi = tblKonsultasi.getValueAt(baris, 1);
            Object objIdPasien = tblKonsultasi.getValueAt(baris, 2);
            Object objIdDokter = tblKonsultasi.getValueAt(baris, 3);
            Object objWaktuKonsultasi = tblKonsultasi.getValueAt(baris, 4);
            Object objCatatan = tblKonsultasi.getValueAt(baris, 5);
            Object objKeperluanPasien = tblKonsultasi.getValueAt(baris, 6);

            String idKonsultasi = objIdKonsultasi != null ? objIdKonsultasi.toString() : "";
            String idPasien = objIdPasien != null ? objIdPasien.toString() : "";
            String idDokter = objIdDokter != null ? objIdDokter.toString() : "";
            String waktuKonsultasi = objWaktuKonsultasi != null ? objWaktuKonsultasi.toString() : "";
            String catatan = objCatatan != null ? objCatatan.toString() : "";
            String keperluanPasien = objKeperluanPasien != null ? objKeperluanPasien.toString() : "";

            // Set nilai ke TextField
            txtHiddenIdKonsultasi.setText(idKonsultasi);
            txtEditWaktu.setText(waktuKonsultasi);
            txtEditCatatan1.setText(catatan);
            txtEditKeluhan1.setText(keperluanPasien);

            // Pilih item pada ComboBox Pasien
            for (int i = 0; i < cbEditNamaPasien.getItemCount(); i++) {
                String item = cbEditNamaPasien.getItemAt(i);
                if (item.contains("ID: " + idPasien)) {
                    cbEditNamaPasien.setSelectedIndex(i);
                    break;
                }
            }

            // Pilih item pada ComboBox Dokter
            for (int i = 0; i < cbEditNamaDokter.getItemCount(); i++) {
                String item = cbEditNamaDokter.getItemAt(i);
                if (item.contains("ID: " + idDokter)) {
                    cbEditNamaDokter.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_tblKonsultasiMouseClicked

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(editKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_editActionPerformed

    private void btSimpanKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanKonsulActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(dataKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            String sql = "UPDATE t_konsultasi SET idPasien = ?, idDokter = ?, waktuKonsultasi = ?, catatan = ?, keperluanPasien = ? WHERE idKonsultasi = ?";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mengambil nilai dari ComboBox dan TextField
            String pasienItem = cbEditNamaPasien.getSelectedItem().toString();
            String dokterItem = cbEditNamaDokter.getSelectedItem().toString();  // Perbaikan: Ambil nilai dari ComboBox Dokter

            // Pastikan format nama (ID: 1)
            int idPasien = Integer.parseInt(pasienItem.substring(pasienItem.indexOf("ID:") + 3, pasienItem.indexOf(")")).trim());
            int idDokter = Integer.parseInt(dokterItem.substring(dokterItem.indexOf("ID:") + 3, dokterItem.indexOf(")")).trim());

            String waktuKonsultasi = txtEditWaktu.getText();
            String catatan = txtEditCatatan1.getText();
            String keperluanPasien = txtEditKeluhan1.getText();
            int idKonsultasi = Integer.parseInt(txtHiddenIdKonsultasi.getText()); // ID Konsultasi yang diupdate

            // Validasi input
            if (waktuKonsultasi.isEmpty() || catatan.isEmpty() || keperluanPasien.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pastikan semua field terisi dengan benar.");
                return;
            }

            // Mengisi parameter ke query
            pst.setInt(1, idPasien); // idPasien
            pst.setInt(2, idDokter); // idDokter
            pst.setString(3, waktuKonsultasi); // waktuKonsultasi
            pst.setString(4, catatan); // catatan
            pst.setString(5, keperluanPasien); // keperluanPasien
            pst.setInt(6, idKonsultasi); // idKonsultasi

            // Menjalankan query
            int rowsAffected = pst.executeUpdate(); // Mengeksekusi update
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
                writeLog("Data berhasil diperbarui untuk Konsultasi dengan ID Konsultasi: " + idKonsultasi);

                // Muat ulang tabel dan bersihkan form
                load_table();
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada perubahan data.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal diperbarui: " + e.getMessage());
            writeLog("Data gagal diperbarui: " + e.getMessage());
        }
    }//GEN-LAST:event_btSimpanKonsulActionPerformed

    private void btBatalKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalKonsulActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(dataKonsul);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btBatalKonsulActionPerformed

    private void txtEditWaktutxtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditWaktutxtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditWaktutxtid1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(txtHiddenIdKonsultasi.getText())) {  // Periksa apakah ID Konsultasi kosong
                JOptionPane.showMessageDialog(this, "Pilih Data Yang ingin dihapus terlebih dahulu");
            } else {
                // Menampilkan konfirmasi sebelum menghapus data
                int confirm = JOptionPane.showConfirmDialog(this,
                        "Apakah Anda yakin ingin menghapus data dengan ID Konsultasi: " + txtHiddenIdKonsultasi.getText(),
                        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                // Jika pengguna memilih YES, lanjutkan menghapus
                if (confirm == JOptionPane.YES_OPTION) {
                    String sql = "DELETE FROM t_konsultasi WHERE idKonsultasi='" + txtHiddenIdKonsultasi.getText() + "'"; // Menggunakan ID Konsultasi
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus dengan ID Konsultasi: " + txtHiddenIdKonsultasi.getText());
                    writeLog("Data Berhasil Dihapus dengan ID Konsultasi: " + txtHiddenIdKonsultasi.getText());
                } else {
                    // Jika pengguna memilih NO, tidak melakukan apa-apa
                    JOptionPane.showMessageDialog(this, "Data Tidak Dihapus");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            writeLog("Data gagal dihapus: " + e.getMessage());
        }

// Memuat ulang tabel setelah data dihapus
        load_table();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtEditKeluhan1txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditKeluhan1txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditKeluhan1txtid1ActionPerformed

    private void txtEditCatatan1txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditCatatan1txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCatatan1txtid1ActionPerformed

    private void txtKeluhantxtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluhantxtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeluhantxtid1ActionPerformed

    private void txtCatatantxtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatatantxtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatatantxtid1ActionPerformed

    private void txtWaktutxtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktutxtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktutxtid1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btBatalKonsul;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btSimpanKonsul;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton bt_edit;
    private javax.swing.JComboBox<String> cbEditNamaDokter;
    private javax.swing.JComboBox<String> cbEditNamaPasien;
    private javax.swing.JComboBox<String> cbLevel1;
    private javax.swing.JComboBox<String> cbLevel3;
    private javax.swing.JComboBox<String> cbTambahNamaDokter;
    private javax.swing.JComboBox<String> cbTambahNamaPasien;
    private javax.swing.JPanel dataKonsul;
    private javax.swing.JPanel editKonsul;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tambahKonsul;
    private javax.swing.JTable tblKonsultasi;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtEditCatatan1;
    private javax.swing.JTextField txtEditKeluhan1;
    private javax.swing.JTextField txtEditWaktu;
    private javax.swing.JTextField txtHiddenIdKonsultasi;
    private javax.swing.JTextField txtKeluhan;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
