/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.Component;

import java.sql.Connection;
//import javaaplikasi_v1.pkg0.Dashboard;
import javax.swing.JOptionPane;
import model.Config;
import static model.Config.writeLog;

/**
 *
 * @author Saidi
 */
public class Form_profilPasien extends javax.swing.JPanel {

    private void loadData(int idPasien) {
        try {
            // Query untuk mendapatkan data pasien berdasarkan idPasien
            String sqlSelect = "SELECT * FROM t_pasien WHERE idPasien = ?";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
            pstSelect.setInt(1, idPasien); // Menggunakan idPasien untuk filter
            java.sql.ResultSet rs = pstSelect.executeQuery();

            if (rs.next()) {
                // Set text field dengan data pasien yang diambil
                txtNamaProfilePasien.setText(rs.getString("namaPasien"));
                cbJenisKelaminProfilePasien.setSelectedItem(rs.getString("jenisKelamin"));
                txtAlamatPasien.setText(rs.getString("alamat"));
                txtHiddenProfile.setText(String.valueOf(idPasien)); // Set idPasien di hidden field
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data pasien: " + e.getMessage());
        }
    }

    /**
     * Creates new form Form_User
     */
    public Form_profilPasien(int idPasien, String namaPasien, String jenisKelamin, String alamat) {
        initComponents();
//        load_table();
        txtHiddenProfile.setVisible(false);
        txtHiddenProfile.setText(String.valueOf(idPasien));
        loadData(idPasien);
//        txtAlamatPasien.setText(alamat);
//        txtNamaProfilePasien.setText(namaPasien);
//        cbJenisKelaminProfilePasien.setSelectedItem(jenisKelamin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        editUSer = new javax.swing.JPanel();
        btEditSimpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHiddenProfile = new javax.swing.JTextField();
        txtNamaProfilePasien = new javax.swing.JTextField();
        txtAlamatPasien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbJenisKelaminProfilePasien = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        editUSer.setBackground(new java.awt.Color(255, 255, 255));
        editUSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btEditSimpan.setBackground(new java.awt.Color(195, 224, 253));
        btEditSimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btEditSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector.png"))); // NOI18N
        btEditSimpan.setText("Simpan");
        btEditSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditSimpanActionPerformed(evt);
            }
        });
        editUSer.add(btEditSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Jenis Kelamin");

        txtNamaProfilePasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaProfilePasien.setToolTipText("");
        txtNamaProfilePasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtNamaProfilePasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProfilePasienActionPerformed(evt);
            }
        });

        txtAlamatPasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAlamatPasien.setToolTipText("");
        txtAlamatPasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtAlamatPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatPasienActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Nama");

        cbJenisKelaminProfilePasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cbJenisKelaminProfilePasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminProfilePasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtAlamatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtHiddenProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenisKelaminProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(txtHiddenProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAlamatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addComponent(cbJenisKelaminProfilePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        editUSer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 480, 270));

        jLabel64.setBackground(new java.awt.Color(102, 102, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 255));
        jLabel64.setText("Edit Biodata");
        editUSer.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        mainPanel.add(editUSer, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenisKelaminProfilePasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminProfilePasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelaminProfilePasienActionPerformed

    private void txtAlamatPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatPasienActionPerformed

    private void txtNamaProfilePasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProfilePasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProfilePasienActionPerformed

    private void btEditSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditSimpanActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(editUSer);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            // Memeriksa apakah Nama Pasien kosong
            if ("".equals(txtNamaProfilePasien.getText())) {
                JOptionPane.showMessageDialog(this, "Isikan Nama Pasien terlebih dahulu");
            } else {
                // Menyusun query untuk update data pasien berdasarkan idPasien
                String sqlUpdate = "UPDATE t_pasien SET namaPasien = '" + txtNamaProfilePasien.getText()
                + "', jenisKelamin = '" + cbJenisKelaminProfilePasien.getSelectedItem().toString()
                + "', alamat = '" + txtAlamatPasien.getText()
                + "' WHERE idPasien = '" + txtHiddenProfile.getText() + "'";

                // Membuka koneksi ke database
                java.sql.Connection conn = (Connection) Config.configDB();

                // Menyiapkan statement dan mengeksekusi query update
                java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                pstUpdate.execute();

                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(null, "Data Pasien Berhasil Diperbaharui dengan Nama " + txtNamaProfilePasien.getText());
                writeLog("Data Pasien Berhasil Diperbaharui dengan ID Pasien " + txtHiddenProfile.getText());

                // Setelah data diperbarui, ambil data terbaru
                String sqlSelect = "SELECT * FROM t_pasien WHERE idPasien = ?";
                java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
                pstSelect.setInt(1, Integer.parseInt(txtHiddenProfile.getText())); // ID pasien yang disembunyikan

                java.sql.ResultSet rs = pstSelect.executeQuery();
                if (rs.next()) {
                    // Update text field dengan data terbaru
                    txtNamaProfilePasien.setText(rs.getString("namaPasien"));
                    cbJenisKelaminProfilePasien.setSelectedItem(rs.getString("jenisKelamin"));
                    txtAlamatPasien.setText(rs.getString("alamat"));
                }
            }
        } catch (Exception e) {
            // Menampilkan pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
            writeLog("Perubahan Data Gagal : " + e.getMessage());
        }
    }//GEN-LAST:event_btEditSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditSimpan;
    private javax.swing.JComboBox<String> cbJenisKelaminProfilePasien;
    private javax.swing.JPanel editUSer;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAlamatPasien;
    private javax.swing.JTextField txtHiddenProfile;
    private javax.swing.JTextField txtNamaProfilePasien;
    // End of variables declaration//GEN-END:variables
}
