/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.Component;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Config;
import static model.Config.writeLog;

/**
 *
 * @author Saidi
 */
public class Form_profilDokters extends javax.swing.JPanel {
        


    private void loadData(int idDokter) {
        try {
            // Query untuk mendapatkan data pasien berdasarkan idPasien
            String sqlSelect = "SELECT * FROM t_dokter WHERE idDokter = ?";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
            pstSelect.setInt(1, idDokter); // Menggunakan idPasien untuk filter
            java.sql.ResultSet rs = pstSelect.executeQuery();

            if (rs.next()) {
                // Set text field dengan data pasien yang diambil
                txtEditNamaDokter.setText(rs.getString("namaDokter"));
                txtEditSpesialis.setText(rs.getString("spesialis"));
                cbEditJenisKelamin.setSelectedItem(rs.getString("jenisKelamin"));
                txtEditRuangan.setText(rs.getString("ruangan"));
                txtHiddeIdDokter.setText(String.valueOf(idDokter)); // Set idPasien di hidden field
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data pasien: " + e.getMessage());
        }
    }

    /**
     * Creates new form Form_dokterKonsul
     */
    public Form_profilDokters(int idDokter) {
        initComponents();
        loadData(idDokter);
        // Mengatur lebar kolom tabel
        txtHiddeIdDokter.setVisible(false); // Menyembunyikan JTextField
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        editProfileDokter = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbEditJenisKelamin = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtHiddeIdDokter = new javax.swing.JTextField();
        txtEditRuangan = new javax.swing.JTextField();
        txtEditSpesialis = new javax.swing.JTextField();
        txtEditNamaDokter = new javax.swing.JTextField();
        btEditSimpan = new javax.swing.JButton();
        btBatal2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbLevel5 = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        editProfileDokter.setBackground(new java.awt.Color(255, 255, 255));
        editProfileDokter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Ruangan");

        cbEditJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Spesialis");

        txtEditRuangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditRuangan.setToolTipText("");
        txtEditRuangan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditRuanganActionPerformed(evt);
            }
        });

        txtEditSpesialis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditSpesialis.setToolTipText("");
        txtEditSpesialis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditSpesialisActionPerformed(evt);
            }
        });

        txtEditNamaDokter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditNamaDokter.setToolTipText("");
        txtEditNamaDokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtEditNamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditNamaDokterActionPerformed(evt);
            }
        });

        btEditSimpan.setBackground(new java.awt.Color(195, 224, 253));
        btEditSimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btEditSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Vector.png"))); // NOI18N
        btEditSimpan.setText("Simpan");
        btEditSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditSimpanActionPerformed(evt);
            }
        });

        btBatal2.setBackground(new java.awt.Color(204, 255, 255));
        btBatal2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btBatal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image 10.png"))); // NOI18N
        btBatal2.setText("Batal");
        btBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatal2ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Nama dokter");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("jenis kelamin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEditNamaDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEditSpesialis))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtEditRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addGap(276, 276, 276))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btEditSimpan)
                                        .addGap(34, 34, 34)
                                        .addComponent(btBatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtHiddeIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cbEditJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel15)))
                .addGap(12, 12, 12)
                .addComponent(txtEditSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(txtHiddeIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cbEditJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(txtEditRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEditSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        editProfileDokter.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 740, 410));

        cbLevel5.setBackground(new java.awt.Color(153, 153, 255));
        cbLevel5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1 (User)", "Level 2 (Pegawai)", "Level 3 (Admin)" }));
        editProfileDokter.add(cbLevel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 224, 364, -1));

        jLabel64.setBackground(new java.awt.Color(102, 102, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 255));
        jLabel64.setText("Edit Biodata Dokter");
        editProfileDokter.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        mainPanel.add(editProfileDokter, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btEditSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditSimpanActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(editProfileDokter);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            // Memeriksa apakah Nama Dokter kosong
            if ("".equals(txtEditNamaDokter.getText())) {
                JOptionPane.showMessageDialog(this, "Isikan Nama Dokter terlebih dahulu");
            } else {
                // Menyusun query untuk update data dokter berdasarkan idDokter
                String sqlUpdate = "UPDATE t_dokter SET namaDokter = '" + txtEditNamaDokter.getText()
                        + "', spesialis = '" + txtEditSpesialis.getText()
                        + "', jenisKelamin = '" + cbEditJenisKelamin.getSelectedItem().toString()
                        + "', ruangan = '" + txtEditRuangan.getText()
                        + "' WHERE idDokter = '" + txtHiddeIdDokter.getText() + "'";

                // Membuka koneksi ke database
                java.sql.Connection conn = (Connection) Config.configDB();

                // Menyiapkan statement dan mengeksekusi query update
                java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                pstUpdate.execute();

                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(null, "Data Dokter Berhasil Diperbaharui dengan Nama " + txtEditNamaDokter.getText());
                writeLog("Data Dokter Berhasil Diperbaharui dengan ID Dokter " + txtHiddeIdDokter.getText());

                // Setelah data diperbarui, ambil data terbaru
                String sqlSelect = "SELECT * FROM t_dokter WHERE idDokter = ?";
                java.sql.PreparedStatement pstSelect = conn.prepareStatement(sqlSelect);
                pstSelect.setInt(1, Integer.parseInt(txtHiddeIdDokter.getText())); // ID dokter yang disembunyikan

                java.sql.ResultSet rs = pstSelect.executeQuery();
                if (rs.next()) {
                    // Update text field dengan data terbaru
                    txtEditNamaDokter.setText(rs.getString("namaDokter"));
                    txtEditSpesialis.setText(rs.getString("spesialis"));
                    cbEditJenisKelamin.setSelectedItem(rs.getString("jenisKelamin"));
                    txtEditRuangan.setText(rs.getString("ruangan"));
                    txtHiddeIdDokter.setText(String.valueOf(rs.getInt("idDokter"))); // Set ID dokter
                }
            }
        } catch (Exception e) {
            // Menampilkan pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
            writeLog("Perubahan Data Gagal : " + e.getMessage());
        }

    }//GEN-LAST:event_btEditSimpanActionPerformed

    private void btBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatal2ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(editProfileDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btBatal2ActionPerformed

    private void txtEditRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditRuanganActionPerformed

    private void txtEditSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditSpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditSpesialisActionPerformed

    private void txtEditNamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditNamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNamaDokterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal2;
    private javax.swing.JButton btEditSimpan;
    private javax.swing.JComboBox<String> cbEditJenisKelamin;
    private javax.swing.JComboBox<String> cbLevel5;
    private javax.swing.JPanel editProfileDokter;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtEditNamaDokter;
    private javax.swing.JTextField txtEditRuangan;
    private javax.swing.JTextField txtEditSpesialis;
    private javax.swing.JTextField txtHiddeIdDokter;
    // End of variables declaration//GEN-END:variables
}
