package src.Component;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import src.Component.MenuItem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saidi
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fNavbar = new javax.swing.JPanel();
        fSidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        Fcontent = new javax.swing.JPanel();
        f_Utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        fNavbar.setBackground(new java.awt.Color(0, 153, 153));
        fNavbar.setPreferredSize(new java.awt.Dimension(1405, 70));

        javax.swing.GroupLayout fNavbarLayout = new javax.swing.GroupLayout(fNavbar);
        fNavbar.setLayout(fNavbarLayout);
        fNavbarLayout.setHorizontalGroup(
            fNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        fNavbarLayout.setVerticalGroup(
            fNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(fNavbar, java.awt.BorderLayout.PAGE_START);

        fSidebar.setBackground(new java.awt.Color(255, 255, 255));
        fSidebar.setPreferredSize(new java.awt.Dimension(250, 495));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout fSidebarLayout = new javax.swing.GroupLayout(fSidebar);
        fSidebar.setLayout(fSidebarLayout);
        fSidebarLayout.setHorizontalGroup(
            fSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        fSidebarLayout.setVerticalGroup(
            fSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        getContentPane().add(fSidebar, java.awt.BorderLayout.LINE_START);

        Fcontent.setBackground(new java.awt.Color(255, 255, 255));

        f_Utama.setBackground(new java.awt.Color(255, 255, 255));
        f_Utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout FcontentLayout = new javax.swing.GroupLayout(Fcontent);
        Fcontent.setLayout(FcontentLayout);
        FcontentLayout.setHorizontalGroup(
            FcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(f_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        FcontentLayout.setVerticalGroup(
            FcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(f_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Fcontent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fcontent;
    private javax.swing.JPanel fNavbar;
    private javax.swing.JPanel fSidebar;
    private javax.swing.JPanel f_Utama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_menu;
    // End of variables declaration//GEN-END:variables

   private void execute() {
    ImageIcon iconUser = new ImageIcon(getClass().getResource("/asset/user.png"));
   
    MenuItem masBarang1 = new MenuItem(null, true, iconUser, "barang1", e -> System.out.println("Barang1 clicked"));
    MenuItem masBarang2 = new MenuItem(null, true, iconUser, "barang2", null);
    MenuItem masBarang3 = new MenuItem(null, true, iconUser, "barang3", null);

    MenuItem trasaksi1 = new MenuItem(null, true, iconUser, "Transaksi1", null);
    MenuItem trasaksi2 = new MenuItem(null, true, iconUser, "Transaksi2", null);
    MenuItem trasaksi3 = new MenuItem(null, true, iconUser, "Transaksi3", null);

    MenuItem menuMaster = new MenuItem(iconUser, false, null, "Master", null, masBarang1, masBarang2, masBarang3);
    MenuItem menuTransaksi = new MenuItem(iconUser, false, null, "Transaksi", null, trasaksi1, trasaksi2, trasaksi3);

    addMenu(menuMaster, menuTransaksi);
}


    private void addMenu(MenuItem... menus) {
    for (MenuItem menu : menus) {
        pn_menu.add(menu);
        for (MenuItem sub : menu.getSubMenu()) {
            addMenu(sub);
        }
    }
    pn_menu.revalidate();
    pn_menu.repaint();
}
}
